CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name <> ''),
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS categories_sort_order_idx
    ON categories (sort_order, name);

INSERT INTO categories (name, sort_order)
VALUES
    ('Furniture', 10),
    ('Art', 20),
    ('Jewelry', 30),
    ('Ceramics & Glass', 40),
    ('Books & Manuscripts', 50),
    ('Coins & Currency', 60),
    ('Clocks & Watches', 70),
    ('Militaria', 80),
    ('Collectibles', 90)
ON CONFLICT (name) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();
